### ISSUE TITLE
Problems with NanoR: NanoPrepareM and NanoTableM

### ISSUE THREAD

**Issue by ssegse** [davidebolo1993/NanoR#20] opened 2021-02-03 11:51 UTC
Hi, 

I'm working on a sequencing dataset produced by the Minion/nanopore method extracted from soil. My data is single-read and in fastaq format, and Im currently just working on the 29 sample set gathered from barcode 1.

Here is my code (some parts are generalized/simplified + comments):

library(BiocManager)

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("rhdf5")
BiocManager::install("ShortRead")

install.packages("/path/NanoR.tar.gz", repos=NULL)
install.packages("seqinr")     
install.packages("reshape2")    
install.packages("RColorBrewer")     
install.packages("ggplot2")  

#remove.packages("NanoR")
library("NanoR")
#NANOG

#DataSummary <-"path/final_summary_FAO01497_8b1d707b.txt"
#DataFastqpassed <-"/path/R/barcode01pass"
#Datafastqfail <- "/path/barcode01_fastqfail"
Datafast5pass <-"path/barcode01_fast5_pass/barcode01"
Datafast5skipped <-"/path/barcode01_fast5skipped"
Datafast5fail <-"/path/barcode01_fast5_fail/barcode01"

#Nanoprepare

Lab<-"Exp1"
List<-NanoPrepareM(Datafast5pass, Datafast5fail, Label = Lab, MultiRead=FALSE)
#List<-NanoPrepareM(Datafast5pass, Datafast5fail, Label = Lab, MultiRead=TRUE)

NanoPrepareM<-function(Datafast5pass,DataFail=NA,DataSkip=NA, MultiRead=FALSE) { 
  List<-list()

PassFiles<-list.files(Datafast5pass, full.names=TRUE, recursive = TRUE, pattern=".fast5")
message('Passed FAST5: ', length(PassFiles))

if (is.na(Datafast5fail)) {
  
  FailFilesLength <- 0
  message('Failed FAST5: ', FailFilesLength)
  
}

else {
  
  if (MultiRead==FALSE) {
    
  FailFilesLength <-length(list.files(Datafast5fail, recursive = TRUE, pattern=".fast5"))
  
    message('Failed FAST5: ', FailFilesLength)
    
    }
  
  else {
    
    library(rhdf5)
    
    FailFiles <- list.files(Datafast5fail, recursive = TRUE, pattern=".fast5", full.names=TRUE)
    message('Failed FAST5: ', length(FailFiles))
    
    FailFilesOrdered <- FailFiles[order(as.numeric(gsub("[^0-9]+", "", FailFiles)))]
    
    First <- FailFilesOrdered[1]
    FileOpen <- H5Fopen(First)
    howmany <- nrow(h5ls(FileOpen, recursive=FALSE, datasetinfo=FALSE))
    H5Fclose(FileOpen)
    
    Last <- FailFilesOrdered[length(FailFilesOrdered)]
    FileOpen <- H5Fopen(Last)
    howmany_ <- nrow(h5ls(FileOpen, recursive=FALSE, datasetinfo=FALSE))
    H5Fclose(FileOpen)
    
    FailFilesLength <- (howmany*(length(FailFiles)-1) + howmany_)
  
  
  }
  
  }

if (is.na(Datafast5skipped)) {
  
  SkipFilesLength <- 0
  message('Skipped FAST5: ', SkipFilesLength)
  
   }

else { 
  
  if (MultiRead==FALSE) { 
    
    SkipFilesLength <- length(list.files(Datafast5skipped, recursive = TRUE, pattern=".fast5"))
    message('Skipped FAST5: ', SkipFilesLength)
    
  
  } 
  
  else { 
    
    library(rhdf5)
    
    SkipFiles <- list.files(Datafast5skipped, recursive = TRUE, pattern=".fast5", full.names=TRUE)
    message('Skipped FAST5: ', length(SkipFiles))
    
    SkipFilesOrdered<-SkipFiles[order(as.numeric(gsub("[^0-9]+", "", SkipFiles)))]
    
    First <- SkipFilesOrdered[1]
    FileOpen <- H5Fopen(First)
    howmany <- nrow(h5ls(FileOpen, recursive=FALSE, datasetinfo=FALSE))
    H5Fclose(FileOpen)
    
    Last <- SkipFilesOrdered[length(SkipFilesOrdered)]
    FileOpen <- H5Fopen(Last)
    howmany_ <- nrow(h5ls(FileOpen, recursive=FALSE, datasetinfo=FALSE))
    H5Fclose(FileOpen)
    
    SkipFilesLength <- (howmany*(length(SkipFiles)-1) + howmany_)
    
 
  }
  
}

List[['fast5']] <- PassFiles
List[['failed']] <- FailFilesLength
List[['skipped']] <- SkipFilesLength
List[['multiread']] <- MultiRead

message("Done")  

return(List)

 }
head(List)

> head(List)
$fast5
 [1] "/path/FAO01497_pass_barcode01_8b1d707b_0.fast5" 
 and so on until  [29]

$failed
[1] 8929

$skipped
[1] 8929

**Does this look correct??**

#NANOtABLEM
>  DataOut <- "/path/Output"
> Table<-NanoTableM(List,DataOut,Cores=6, )
Error in if (NanoMList$multiread == FALSE) { : argument is of length zero
> 

Should i put multithread==true? I think my samples are by default single-read from nanopore sequencing by minion. Im sorry for my untidy code, i am quite new to R. If anyone have any suggestions on how to solve this, i would be very grateful. Please let me know if there is anymore information about my code that should be submitted.

Best, 

SSE

**Comment by davidebolo1993** [comment] 2021-02-03 15:37
Hi @ssegse,

sorry but I'm a little bit confused. Assuming you have the NanoR folder cloned from github in your home (something like /home/ssegse/NanoR), I would say that the correct way to install and run NanoR with FASTQ and summary TXT from a MinION/GridION run should be:

``` R
#the following functions take care of the installation of dependencies

Cpak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE, repos="http://cran.cnr.berkeley.edu/")
    sapply(pkg, require, character.only = TRUE)
}

packages <- c("ggplot2","reshape2","RColorBrewer","scales","gridExtra","data.table")
Cpak(packages)

Bpak<- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg))
        if (!requireNamespace("BiocManager", quietly = TRUE))
            install.packages("BiocManager")
        BiocManager::install(new.pkg)
    sapply(pkg, require, character.only = TRUE)
}
packages<-c("rhdf5", "ShortRead")
Bpak(packages)

#install NanoR if not in library

if (!requireNamespace('NanoR', quietly = TRUE))
 install.packages('/home/ssegse/NanoR/NanoR.tar.gz',repos=NULL)

#run NanoR in G mode with sequencing summary and fastq files

summary<-file.path("/path/to/sequencing_summary.txt") #path to sequencing summary .txt
fastq<-file.path("/path/to/fastq_pass.folder")) #path to fastq_pass folder
output<-file.path("/path/to/result_dir") #path to output

Glist<-NanoPrepareG(DataSummary=summary,DataFastq=fastq)
Gtable<-NanoTableG(NanoGList=Glist, DataOut=output, GCC=FALSE)
NanoStatsG(NanoGList=Glist, NanoGTable=Gtable, DataOut=output, KeepGGObj = FALSE)
``` 
You have of course to change paths for summary, fastq and output files accordingly. 
Let me know if I can help further !


Best,

Davide

**Comment by ssegse** [comment] 2021-02-04 09:49
Hi Davide, 

Thank you for the advice. I have used the approach described here: https://github.com/davidebolo1993/NanoR/tree/master/src 
to use the NanoR on my data. 

The code works well, but I get an error when i try to make the g. table: 

>Glist <- NanoPrepareG(DataSummary=summary,DataFastq=fastq)
> Gtable <- NanoTableG(NanoGList=Glist, DataOut=output, GCC=FALSE)
Error: $ operator is invalid for atomic vectors 


Could that error occure because I use the final_summary file instead of the sequencing_summary file?
I have a sequencing summary file, but its very, very big (3,42GB) so I'm not able to download it on my computer from mye onedrive account. I have tried to use the final_summary file instad, but that was probably a stupid idea. 
Do you have any advice on how I can work around this problem?


Thanks again. 


Best, 

sse

**Comment by davidebolo1993** [comment] 2021-02-04 10:14
Hi @ssegse,

Yep, this is probably because the final_summary TSV you have is somehow different from the classic sequencing_summary generated by guppy/albacore. Handling large files is not a big issue usually for NanoR (large tables are loaded quickly and efficiently) but, if I got it right, it is more something related to your workstation. Have you tried the M version with basecalled FAST5? This is usually slower, but maybe that works for you. See instructions [here](https://davidebolo1993.github.io/nanordoc/usage/usage.html#basecalled-fast5).
Let me know if I can help further !

Best,

Davide

**Comment by ssegse** [comment] 2021-02-04 11:33
Hi Davide, 

Thanks for your advice. I now tried the FAST5 basecalled appraoch, but I get this error: 

> sequencing_run <- "path/"
> pass <- file.path(sequencing_run,"barcode01_fast5_pass")
> fail <- file.path(sequencing_run,"barcode01_fast5_fail")
> skip <- file.path(sequencing_run,"barcode01_fast5skipped")
> output <- file.path("path/Output") #path to output
> Mlist <- NanoPrepareM(DataPass=pass,DataFail=fail,DataSkip=skip, MultiRead=TRUE) #multi-read FAST5 are the default output format. Simply switch to FALSE if dealing with single-read FAST5
Error in NanoPrepareM(DataPass = pass, DataFail = fail, DataSkip = skip,  : 
  unused argument (DataPass = pass) 
  
  Do you see any errors in my code?
  
  
  Best, 
Ssegse

**Comment by davidebolo1993** [comment] 2021-02-04 11:47
Hi @ssegse,

as a general suggestion, it would be good not to modify the original functions a package, unless you have a deep insight into a certain programming language. NanoR (NanoPrepareM) accepts a DataPass parameter. However, as from your original comment on this issue, it seems to me that the DataPass parameter has been changed to Datafast5pass (this is not in the original code and I can confirm this). Just to clear up the confusion on this piece of code, I can suggest to uninstall (before) and re-install a fresh version of NanoR. This should solve all the issues you got into recently.

Best,

Davide

**Comment by ssegse** [comment] 2021-02-04 14:05
Hi Davide, 

Thank you  very much for your help. I'm quite new to R, and my questions probably reflect this. 

After I re-installed NanoR, the code works. However, I get some warning and my plot looks a bit weird.  

> library(NanoR)
> sequencing_run <- "/pathr/"
> pass <- file.path(sequencing_run,"barcode01_fast5_pass")
> fail <- file.path(sequencing_run,"barcode01_fast5_fail")
> skip <- file.path(sequencing_run,"barcode01_fast5skipped")
> output <- file.path("/path/Output") #path to output
> Mlist <- NanoPrepareM(DataPass=pass,DataFail=fail,DataSkip=skip, MultiRead=TRUE) #multi-read FAST5 are the default output format. Simply switch to FALSE if dealing with single-read FAST5
Passed FAST5: 29
Failed FAST5: 3
Skipped FAST5: 3
Done
> Mtable<-NanoTableM(NanoMList=Mlist, DataOut=output, Cores=6, GCC=FALSE) #increase the number of cores to increase speed if dealing with a large number of FAST5; switch GCC to TRUE to enable calculation of GC content
Extracting metadata. Multi-read FAST5
Done
> NanoStatsM(NanoMList=Mlist, NanoMTable=Mtable, DataOut=output, KeepGGObj = FALSE)
Analyzing...
Plotting...
`geom_smooth()` using formula 'y ~ x'
Done
Warning messages:
1: Use of `Tot$Template_Length` is discouraged. Use `Template_Length` instead. 
2: Use of `Tot$Quality_Score` is discouraged. Use `Quality_Score` instead. 
3: Use of `Tot$Template_Length` is discouraged. Use `Template_Length` instead. 
4: Use of `Tot$Quality_Score` is discouraged. Use `Quality_Score` instead. 
5: Use of `Tot$Template_Length` is discouraged. Use `Template_Length` instead. 
6: Use of `Tot$Quality_Score` is discouraged. Use `Quality_Score` instead. 
7: In melt(rotate(t(Matrixbpchannel))) :
  The melt generic in data.table has been passed a matrix and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(rotate(t(Matrixbpchannel))). In the next version, this warning will become an error.
8: In melt(rotate(t(MatrixMuxActivity))) :
  The melt generic in data.table has been passed a matrix and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(rotate(t(MatrixMuxActivity))). In the next version, this warning will become an error.
> 

![image](https://user-images.githubusercontent.com/78480945/106903535-635f9e00-66fa-11eb-8fa5-5dda4877a604.png)

Is this warning message normal? 


Best, ssegse

**Comment by davidebolo1993** [comment] 2021-02-05 10:11
Hi @ssegse, 

this is somehow related to the packages version you are using in your R environment, I suppose. It would be helpful if you can share the loaded packages with your versions. Something like

``` R
library(NanoR)
sessionInfo()
```
Maybe I need to update part of the code in order to make NanoR compatible with more recent versions of reshape2. In that case, sharing your data could be useful as well. 

Thanks,

Davide

**Comment by davidebolo1993** [comment] 2021-02-17 11:38
Hi @ssegse,

any updates on this?

**Comment by davidebolo1993** [comment] 2021-02-25 11:39
Closing, but feel free to re-open at any time

**Closed by davidebolo1993** 2021-02-25 11:39 UTC
Labels: question
